Artifactory:
  server: <your server> #change to your servername
  intName: artifactory_integration
  devRepo: workshop-docker-local
  prodRepo: workshop-docker-prod-local
  creds: pull_secrets
GitHub:
  path: <github username>/aws-ecs-docker-compose-workshop #change to your github username
  gitProvider: github_integration
AWS:
  intName: aws_integration
  region: us-west-2
app:
  dockerImageName: <your server>/workshop-docker/ecs-docker-compose-workshop-app #change to your servername
  dockerFileLocation: workshop-app
  buildName: ecs-docker-compose-workshop-app
